package com.personal.plan.elasticsearch.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.personal.plan.elasticsearch.config.CamelToSnakeCaseUpper;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

@Data
@Document(indexName="planinfo")
@JsonNaming(CamelToSnakeCaseUpper.class)
public class Plan{
    @Id
    @JsonIgnore
    private String _id;
    private String ACK_ID;
    private String FORM_PLAN_YEAR_BEGIN_DATE;
    private String FORM_TAX_PRD;
    private String TYPE_PLAN_ENTITY_CD;
    private String TYPE_DFE_PLAN_ENTITY_CD;
    private String INITIAL_FILING_IND;
    private String AMENDED_IND;
    private String FINAL_FILING_IND;
    private String SHORT_PLAN_YR_IND;
    private String COLLECTIVE_BARGAIN_IND;
    private String F5558_APPLICATION_FILED_IND;
    private String EXT_AUTOMATIC_IND;
    private String DFVC_PROGRAM_IND;
    private String EXT_SPECIAL_IND;
    private String EXT_SPECIAL_TEXT;
    private String PLAN_NAME;
    private String SPONS_DFE_PN;
    private String PLAN_EFF_DATE;
    private String SPONSOR_DFE_NAME;
    private String SPONS_DFE_DBA_NAME;
    private String SPONS_DFE_CARE_OF_NAME;
    private String SPONS_DFE_MAIL_US_ADDRESS1;
    private String SPONS_DFE_MAIL_US_ADDRESS2;
    private String SPONS_DFE_MAIL_US_CITY;
    private String SPONS_DFE_MAIL_US_STATE;
    private String SPONS_DFE_MAIL_US_ZIP;
    private String SPONS_DFE_MAIL_FOREIGN_ADDR1;
    private String SPONS_DFE_MAIL_FOREIGN_ADDR2;
    private String SPONS_DFE_MAIL_FOREIGN_CITY;
    private String SPONS_DFE_MAIL_FORGN_PROV_ST;
    private String SPONS_DFE_MAIL_FOREIGN_CNTRY;
    private String SPONS_DFE_MAIL_FORGN_POSTAL_CD;
    private String SPONS_DFE_LOC_US_ADDRESS1;
    private String SPONS_DFE_LOC_US_ADDRESS2;
    private String SPONS_DFE_LOC_US_CITY;
    private String SPONS_DFE_LOC_US_STATE;
    private String SPONS_DFE_LOC_US_ZIP;
    private String SPONS_DFE_LOC_FOREIGN_ADDRESS1;
    private String SPONS_DFE_LOC_FOREIGN_ADDRESS2;
    private String SPONS_DFE_LOC_FOREIGN_CITY;
    private String SPONS_DFE_LOC_FORGN_PROV_ST;
    private String SPONS_DFE_LOC_FOREIGN_CNTRY;
    private String SPONS_DFE_LOC_FORGN_POSTAL_CD;
    private String SPONS_DFE_EIN;
    private String SPONS_DFE_PHONE_NUM;
    private String BUSINESS_CODE;
    private String ADMIN_NAME;
    private String ADMIN_CARE_OF_NAME;
    private String ADMIN_US_ADDRESS1;
    private String ADMIN_US_ADDRESS2;
    private String ADMIN_US_CITY;
    private String ADMIN_US_STATE;
    private String ADMIN_US_ZIP;
    private String ADMIN_FOREIGN_ADDRESS1;
    private String ADMIN_FOREIGN_ADDRESS2;
    private String ADMIN_FOREIGN_CITY;
    private String ADMIN_FOREIGN_PROV_STATE;
    private String ADMIN_FOREIGN_CNTRY;
    private String ADMIN_FOREIGN_POSTAL_CD;
    private String ADMIN_EIN;
    private String ADMIN_PHONE_NUM;
    private String LAST_RPT_SPONS_NAME;
    private String LAST_RPT_SPONS_EIN;
    private String LAST_RPT_PLAN_NUM;
    private String ADMIN_SIGNED_DATE;
    private String ADMIN_SIGNED_NAME;
    private String SPONS_SIGNED_DATE;
    private String SPONS_SIGNED_NAME;
    private String DFE_SIGNED_DATE;
    private String DFE_SIGNED_NAME;
    private String TOT_PARTCP_BOY_CNT;
    private String TOT_ACTIVE_PARTCP_CNT;
    private String RTD_SEP_PARTCP_RCVG_CNT;
    private String RTD_SEP_PARTCP_FUT_CNT;
    private String SUBTL_ACT_RTD_SEP_CNT;
    private String BENEF_RCVG_BNFT_CNT;
    private String TOT_ACT_RTD_SEP_BENEF_CNT;
    private String PARTCP_ACCOUNT_BAL_CNT;
    private String SEP_PARTCP_PARTL_VSTD_CNT;
    private String CONTRIB_EMPLRS_CNT;
    private String TYPE_PENSION_BNFT_CODE;
    private String TYPE_WELFARE_BNFT_CODE;
    private String FUNDING_INSURANCE_IND;
    private String FUNDING_SEC412_IND;
    private String FUNDING_TRUST_IND;
    private String FUNDING_GEN_ASSET_IND;
    private String BENEFIT_INSURANCE_IND;
    private String BENEFIT_SEC412_IND;
    private String BENEFIT_TRUST_IND;
    private String BENEFIT_GEN_ASSET_IND;
    private String SCH_R_ATTACHED_IND;
    private String SCH_MB_ATTACHED_IND;
    private String SCH_SB_ATTACHED_IND;
    private String SCH_H_ATTACHED_IND;
    private String SCH_I_ATTACHED_IND;
    private String SCH_A_ATTACHED_IND;
    private String NUM_SCH_A_ATTACHED_CNT;
    private String SCH_C_ATTACHED_IND;
    private String SCH_D_ATTACHED_IND;
    private String SCH_G_ATTACHED_IND;
    private String FILING_STATUS;
    private String DATE_RECEIVED;
    private String VALID_ADMIN_SIGNATURE;
    private String VALID_DFE_SIGNATURE;
    private String VALID_SPONSOR_SIGNATURE;
    private String ADMIN_PHONE_NUM_FOREIGN;
    private String SPONS_DFE_PHONE_NUM_FOREIGN;
    private String ADMIN_NAME_SAME_SPON_IND;
    private String ADMIN_ADDRESS_SAME_SPON_IND;
    private String PREPARER_NAME;
    private String PREPARER_FIRM_NAME;
    private String PREPARER_US_ADDRESS1;
    private String PREPARER_US_ADDRESS2;
    private String PREPARER_US_CITY;
    private String PREPARER_US_STATE;
    private String PREPARER_US_ZIP;
    private String PREPARER_FOREIGN_ADDRESS1;
    private String PREPARER_FOREIGN_ADDRESS2;
    private String PREPARER_FOREIGN_CITY;
    private String PREPARER_FOREIGN_PROV_STATE;
    private String PREPARER_FOREIGN_CNTRY;
    private String PREPARER_FOREIGN_POSTAL_CD;
    private String PREPARER_PHONE_NUM;
    private String PREPARER_PHONE_NUM_FOREIGN;
    private String TOT_ACT_PARTCP_BOY_CNT;
    private String SUBJ_M1_FILING_REQ_IND;
    private String COMPLIANCE_M1_FILING_REQ_IND;
    private String M1_RECEIPT_CONFIRMATION_CODE;
    private String ADMIN_MANUAL_SIGNED_DATE;
    private String ADMIN_MANUAL_SIGNED_NAME;
    private String LAST_RPT_PLAN_NAME;
    private String SPONS_MANUAL_SIGNED_DATE;
    private String SPONS_MANUAL_SIGNED_NAME;
    private String DFE_MANUAL_SIGNED_DATE;
    private String DFE_MANUAL_SIGNED_NAM;
}
